# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_pb2 as test__pb2


class SquareServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.squareNumber = channel.unary_unary(
                '/SquareService/squareNumber',
                request_serializer=test__pb2.Number.SerializeToString,
                response_deserializer=test__pb2.Number.FromString,
                )


class SquareServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def squareNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SquareServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'squareNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.squareNumber,
                    request_deserializer=test__pb2.Number.FromString,
                    response_serializer=test__pb2.Number.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SquareService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SquareService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def squareNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SquareService/squareNumber',
            test__pb2.Number.SerializeToString,
            test__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
