# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x33\n\rSquareService\x12\"\n\x0csquareNumber\x12\x07.Number\x1a\x07.Number\"\x00\x62\x06proto3')



_NUMBER = DESCRIPTOR.message_types_by_name['Number']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  })
_sym_db.RegisterMessage(Number)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)

_SQUARESERVICE = DESCRIPTOR.services_by_name['SquareService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NUMBER._serialized_start=14
  _NUMBER._serialized_end=37
  _RESULT._serialized_start=39
  _RESULT._serialized_end=63
  _SQUARESERVICE._serialized_start=65
  _SQUARESERVICE._serialized_end=116
# @@protoc_insertion_point(module_scope)
